# docker compose up --build
services:
  builder:
    container_name: builder-alacritty

    volumes:
      - ./target:/target

    #tty: true
    #stdin_open: true

    command: >
      /bin/bash -c "
      export CARGO_HOME=/target/rust/cargo/home RUSTUP_HOME=/target/rust/rustup/home
      && rustup default 1.91.0
      && { [[ -d alacritty ]] || git clone https://github.com/alacritty/alacritty.git ; }
      && cd alacritty
      && git fetch -apt
      && git checkout v0.16.1
      && cargo build --release --no-default-features --features=wayland
      "

    build:
      context: .
      dockerfile_inline: |
        FROM docker.io/rust:1.91.0-slim-trixie
        USER root
        RUN apt-get update && apt-get --yes install cmake g++ git pkg-config \
            libfontconfig1-dev libxcb-xfixes0-dev libxkbcommon-dev python3
        WORKDIR /target
