---
version: '0.2'

ignorePaths:
  - '*/src'
  - '*/out'

dictionaries:
  - en_US
  - softwareTerms
  - bash

words:
  - lockscreen

ignoreWords:
  # names
  - georglauterbach
  - firacode
  - patorjk

  # theme
  - everforest
  - evergruv
  - gruvbox
  - yaru

  # Sway
  - swaybg
  - swayfx
  - swayidle
  - swayimg
  - swaylock
  - swaymsg
  - swaync
  - swaynotificationcenter
  - xwayland

  # packages
  - btop
  - ianny
  - lightctl
  - patchelf
  - pipewire
  - rofi
  - satty
  - shikane
  - waybar
  - wdisplays
  - wireplumber
  - wl-screenrec
  - wleave
  - wlsunset

  # commands
  - gsettings
  - rustup
  - shikanectl
  - wpctl

  # acronyms
  - PKCS11

  # miscellaneous
  - bindsym
  - containerfile
  - coolors
  - SIGUSR
