version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words: []
import: []

ignoreWords:
  - alacritty
  - bindsym
  - dbus
  - everforest
  - gruvbox
  - nodeadkeys
  - numlock
  - pipewire
  - rofi
  - swayfx
  - swayidle
  - swaylock
  - swaync
  - waybar
  - wireplumber
  - wlroots
  - xwayland

