---
version: '0.2'

import:
  - custom/wayland/cspell.config.yaml

dictionaries:
  - en_US
  - softwareTerms
  - bash

words: []

# ignoreWords:
#   - alacritty
#   - bindsym
#   - dbus
#   - everforest
#   - flatpak
#   - flatpaks
#   - gruvbox
#   - nodeadkeys
#   - numlock
#   - pipefail
#   - pipewire
#   - rofi
#   - ryzen
#   - swayfx
#   - swayidle
#   - swaylock
#   - swaync
#   - uefi
#   - waybar
#   - wireplumber
#   - wlroots
#   - xwayland
#   - yubikey
