font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

background #FFFBEF
foreground #5C6A72

selection_background #5C6A72
selection_foreground #FFFBEF

cursor #5C6A72
cursor_text_color background

# Black
color0  #3c474d
color8  #868d80

# Red
color1                #F85552
color9                #F85552

# Green
color2                #8DA101
color10               #8DA101

# Yellow
color3                #F57D26
color11               #DFA000

# Blue
color4                #3A94C5
color12               #3A94C5

# Magenta
color5                #DF69BA
color13               #DF69BA

# Cyan
color6                #35A77C
color14               #35A77C

# White / Grey
color7                #A6B0A0
color15               #A6B0A0
