#! /bin/sh

set -e -u

GIT_URI=${1:?URI for cloning is required}
GIT_REV=${2:?git revision is required}
shift 2

DIR_NAME=$(printf '%s' "${GIT_URI}" | sed -E 's|.*/(.*)\.git$|\1|')

if [ -d "${DIR_NAME}" ]; then
  cd "${DIR_NAME}"
  if git checkout "${GIT_REV}" >/dev/null 2>&1; then
    __log "Project '${DIR_NAME}' exists in correct version '${GIT_REV}'"
    exit 0
  else
    __log "Project '${DIR_NAME}' exists in wrong version '${GIT_REV}' - removing and cloning again"
    cd ..
    rm -rf "${DIR_NAME}"
  fi
fi

__log "Cloning ${DIR_NAME} @ ${GIT_REV}"
git clone --quiet --depth 1 --branch "${GIT_REV}" "${GIT_URI}"
