[[profile]]
name = "default"
exec = ["notify-send --transient --icon=/usr/share/icons/Adwaita/scalable/devices/video-display.svg \"Displays Configuration\" \"Profile $SHIKANE_PROFILE_NAME has been applied\""]
