---
version: '0.2'

ignorePaths:
  - '*/src'
  - '*/out'

words: []

ignoreWords:
  - Alexays
  - davatorium
  - ErikReider
  - libinput
  - libxcb
  - pipewire
  - pixman
  - rofi
  - scenefx
  - swayfx
  - SwayNotificationCenter
  - swaywm
  - swaybg
  - swayidle
  - swaylock
  - Waybar
  - wireplumber
  - wlrfx
  - xorg
