# docker compose up --build
services:
  builder:
    container_name: builder-waybar

    volumes:
      - ./target:/target

    #tty: true
    #stdin_open: true

    command: >
      /bin/bash -c "
      set -eE -u -o pipefail
      && { [[ -d Waybar ]] || git clone https://github.com/Alexays/Waybar ; }
      && cd Waybar
      && git fetch -apt
      && git checkout 0.14.0
      && meson setup build --reconfigure --prefix=/usr/local -Drfkill=enabled -Dwireplumber=enabled
      && ninja -C build/
      && sleep 1000
      "

    build:
      context: .
      dockerfile_inline: |
        FROM docker.io/ubuntu:25.04
        USER root
        WORKDIR /target

        RUN apt-get --yes update && apt-get --yes install \
          clang-tidy cmake git meson \
          cava \
          gobject-introspection \
          libdbusmenu-gtk3-dev \
          libevdev-dev \
          libfmt-dev \
          libgirepository1.0-dev \
          libgtk-3-dev \
          libgtk4-layer-shell-dev \
          libgtkmm-3.0-dev \
          libiniparser-dev \
          libinotifytools0-dev \
          libinput-dev \
          libjsoncpp-dev \
          libmpdclient-dev \
          libnl-3-dev \
          libnl-genl-3-dev \
          libsigc++-2.0-dev \
          libsndio-dev \
          libspdlog-dev \
          libwayland-dev \
          libwireplumber-0.5-dev \
          libxkbregistry-dev \
          rfkill \
          scdoc \
          upower \
          wayland-protocols
