# docker compose up --build
services:
  builder:
    container_name: builder-waybar

    volumes:
      - ./target:/target

    tty: true
    stdin_open: true

    command: >
      /bin/bash -c
      "cd /target
      && ( git clone https://github.com/Alexays/Waybar . || : ; )
      && git fetch -apt
      && git checkout cae5f9a
      && rm -rf build .prefix
      && meson setup build --prefix=/target/.prefix -Drfkill=enabled -Dwireplumber=enabled
      && ninja -C build
      && rm -rf .prefix/share
      && ninja -C build install"

    build:
      context: .
      dockerfile_inline: |
        FROM docker.io/ubuntu:25.04

        RUN apt-get --yes update
        RUN apt-get --yes update && apt-get --yes install git \
          libwireplumber-0.5-dev \
          rfkill \
          libinotifytools0-dev \
          libgtk4-layer-shell-dev \
          cava \
          libiniparser-dev \
          libsndio-dev \
          cmake \
          meson \
          scdoc \
          wayland-protocols \
          clang-tidy \
          gobject-introspection \
          libdbusmenu-gtk3-dev \
          libevdev-dev \
          libfmt-dev \
          libgirepository1.0-dev \
          libgtk-3-dev \
          libgtkmm-3.0-dev \
          libinput-dev \
          libjsoncpp-dev \
          libmpdclient-dev \
          libnl-3-dev \
          libnl-genl-3-dev \
          libsigc++-2.0-dev \
          libspdlog-dev \
          libwayland-dev \
          scdoc \
          upower \
          libxkbregistry-dev \
