VERSION 0.8

FROM docker.packages.rsint.net/rs_common/rs-ubuntu:24.04
USER root

ENV PATH=/root/.local/bin:$PATH
ENV LD_LIBRARY_PATH=/usr/local/lib/x86_64-linux-gnu

RUN apt-get update \
    && apt-get install --quiet --yes --no-install-recommends \
        bash-completion \
        curl \
        file \
        openssl \
        tar \
        wget \
        xz-utils \
        \
        bison \
        build-essential \
        clang \
        cmake \
        flex \
        gcc \
        gettext \
        git \
        nasm \
        ninja-build \
        pkg-config \
        scdoc \
        \
        lua5.4 \
        liblua5.4-0 \
        liblua5.4-dev \
        \
        python3 \
        python3-docutils \
        python3-setuptools \
        python3-dev \
        pipx \
        \
        dbus \
        libdrm-dev \
        libffi-dev \
        libpam0g-dev \
        libpcre2-dev \
        libseccomp-dev \
        libssl-dev \
        libsystemd-dev \
        libudev-dev \
        shared-mime-info \
        systemd

RUN git config --global advice.detachedHead false
RUN pipx install meson
RUN curl -sSfL https://sh.rustup.rs | sh -s -- -y --default-toolchain 1.92.0

WORKDIR /src
COPY functions.sh /do

prepare-repositories:
    RUN /do prepare_sources https://gitlab.freedesktop.org/wayland/wayland.git 1.24
    RUN /do prepare_sources https://gitlab.freedesktop.org/wayland/wayland-protocols.git 1.47

    RUN /do prepare_sources https://gitlab.freedesktop.org/libinput/libinput.git 1.30.1
    RUN /do prepare_sources https://gitlab.freedesktop.org/pixman/pixman.git pixman-0.46.4

    RUN /do prepare_sources https://gitlab.freedesktop.org/xorg/proto/xorgproto.git xorgproto-2025.1
    RUN /do prepare_sources https://gitlab.freedesktop.org/xorg/xserver.git xwayland-24.1.9

    RUN /do prepare_sources https://gitlab.freedesktop.org/wlroots/wlroots.git 0.19.2
    RUN /do prepare_sources https://github.com/wlrfx/scenefx.git 0.4.1
    #RUN /do prepare_sources https://github.com/swaywm/sway.git 1.11
    RUN /do prepare_sources https://github.com/WillPower3309/swayfx.git 0.5.3

    RUN /do prepare_sources https://github.com/Alexays/Waybar.git 0.14.0
    RUN /do prepare_sources https://github.com/davatorium/rofi.git next
    RUN /do prepare_sources https://github.com/ErikReider/SwayNotificationCenter.git v0.11.0
    RUN /do prepare_sources https://github.com/blurrycat/lightctl.git main
    RUN /do prepare_sources https://gitlab.com/w0lff/shikane.git master
    RUN /do prepare_sources https://github.com/ErikReider/SwayAudioIdleInhibit.git main
    RUN /do prepare_sources https://github.com/swaywm/swaybg.git master
    RUN /do prepare_sources https://github.com/swaywm/swayidle.git master
    RUN /do prepare_sources https://github.com/swaywm/swaylock.git v1.8.4
    RUN /do prepare_sources https://github.com/AMNatty/wleave.git development
    RUN /do prepare_sources https://gitlab.freedesktop.org/emersion/grim.git v1.5.0
    RUN /do prepare_sources https://github.com/Satty-org/Satty.git main
    RUN /do prepare_sources https://github.com/emersion/slurp.git v1.5.0
    RUN /do prepare_sources https://github.com/alacritty/alacritty.git v0.16.1

wayland:
    FROM +prepare-repositories

    RUN /do build wayland meson_ninja \
        -Dlibraries=true              \
        -Dscanner=true                \
        -Dtests=false                 \
        -Ddocumentation=false         \
        -Ddtd_validation=false

    RUN /do build wayland-protocols meson_ninja -Dtests=false

generic-dependencies:
    FROM +wayland

    RUN /do apt_install libevdev-dev libmtdev-dev
    RUN /do build libinput meson_ninja \
        -Dlibwacom=false               \
        -Dmtdev=false                  \
        -Ddebug-gui=false              \
        -Dtests=false                  \
        -Ddocumentation=false

    RUN /do build pixman meson_ninja -Dtests=disabled -Ddemos=disabled

xorg:
    FROM +generic-dependencies

    RUN /do build xorgproto meson_ninja

    RUN /do apt_install   \
        libx11-dev        \
        libxshmfence-dev  \
        x11-xkb-utils     \
        libxkbfile-dev    \
        libxkbfile-dev    \
        libxfont-dev      \
        libxcvt-dev       \
        libepoxy-dev      \
        mesa-common-dev   \
        libtirpc-dev      \
        libxcb-xinput-dev \
        libxcb-sync-dev   \
        libxcb-damage0-dev
    RUN /do build xserver meson_ninja -Ddocs=false

    RUN /do finalize_runtime_libs

sway:
    FROM +xorg

    RUN /do apt_install         \
        libxkbcommon-dev        \
        libgbm-dev              \
        libvulkan-dev           \
        glslang-dev             \
        glslang-tools           \
        liblcms2-dev            \
        libseat-dev             \
        hwdata                  \
        libdisplay-info-dev     \
        libliftoff-dev          \
        libxcb-dri3-dev         \
        libxcb-present-dev      \
        libxcb-composite0-dev   \
        libxcb-render-util0-dev \
        libxcb-shm0-dev         \
        libxcb-xfixes0-dev      \
        libxcb-xinput-dev       \
        libxcb-ewmh-dev         \
        libxcb-icccm4-dev       \
        libxcb-res0-dev libgles-dev
    RUN /do build wlroots meson_ninja \
        -Dxwayland=enabled            \
        -Dexamples=false              \
        -Drenderers=gles2,vulkan      \
        -Dbackends=drm,libinput,x11   \
        -Dsession=enabled             \
        -Dcolor-management=enabled    \
        -Dlibliftoff=enabled

    RUN /do build scenefx meson_ninja -Dexamples=false

    RUN /do apt_install            \
        libjson-c-dev              \
        libcairo-dev               \
        libgdk-pixbuf-2.0-dev      \
        libgdk-pixbuf-xlib-2.0-dev \
        libpango1.0-dev
    #RUN /do build sway meson_ninja
    RUN /do build swayfx meson_ninja \
        -Ddefault-wallpaper=false    \
        -Dzsh-completions=false      \
        -Dbash-completions=false     \
        -Dfish-completions=false     \
        -Dswaybar=false              \
        -Dswaynag=false              \
        -Dtray=enabled               \
        -Dgdk-pixbuf=enabled         \
        -Dman-pages=enabled          \
        -Dsd-bus-provider=libsystemd

    RUN /do finalize_runtime_libs

associates:
    FROM +sway

    COPY custom_build_functions.sh /cbf

    RUN . /cbf ; . /do build alacritty              build_alacritty
    RUN . /cbf ; . /do build grim                   meson_ninja
    RUN . /cbf ; . /do build lightctl               build_lightctl
    RUN . /cbf ; . /do build rofi                   meson_ninja -Dxcb=disabled -Dwayland=enabled
    RUN . /cbf ; . /do build slurp                  meson_ninja
    RUN . /cbf ; . /do build SwayAudioIdleInhibit   meson_ninja -Dlogind-provider=systemd
    RUN . /cbf ; . /do build swaybg                 meson_ninja
    RUN . /cbf ; . /do build swayidle               meson_ninja
    RUN . /cbf ; . /do build swaylock               meson_ninja -Dpam=enabled
    RUN . /cbf ; . /do build SwayNotificationCenter meson_ninja
    RUN . /cbf ; . /do build Satty                  build_satty
    RUN . /cbf ; . /do build shikane                build_shikane
    RUN . /cbf ; . /do build wleave                 build_wleave
    RUN . /cbf ; . /do build Waybar                 meson_ninja \
        -Dlibinput=enabled     \
        -Dlibnl=enabled        \
        -Dlibudev=enabled      \
        -Dlibevdev=enabled     \
        -Dpipewire=enabled     \
        -Dsystemd=disabled     \
        -Ddbusmenu-gtk=enabled \
        -Dman-pages=enabled    \
        -Drfkill=enabled       \
        -Dtests=disabled       \
        -Dwireplumber=enabled  \
        -Dcava=disabled        \
        -Dlogin-proxy=true

    RUN /do finalize_runtime_libs

finish:
    FROM +associates

    SAVE ARTIFACT /usr/local AS LOCAL ./out
