# docker compose up --build
services:
  builder:
    container_name: builder-rofi

    volumes:
      - ./target:/target

    #tty: true
    #stdin_open: true

    command: >
      /bin/bash -c "
      set -eE -u -o pipefail
      && { [[ -d rofi ]] || git clone https://github.com/davatorium/rofi.git ; }
      && cd rofi
      && git fetch -apt
      && git checkout 2.0.0
      && meson setup build --reconfigure --prefix=/usr/local
      && ninja -C build
      "

    build:
      context: .
      dockerfile_inline: |
        FROM docker.io/ubuntu:24.04
        USER root
        WORKDIR /target

        RUN apt-get update && apt-get --yes install \
            automake bison cmake flex gcc git make meson ninja-build pkg-config \
            libcairo2 \
            libgdk-pixbuf-2.0-dev \
            libglib2.0-dev \
            libpango1.0-dev \
            libpangocairo-1.0-0 \
            libstartup-notification0-dev \
            libwayland-* \
            libxkbcommon-dev \
            wayland-protocols
