# docker compose up --build
services:
  builder:
    container_name: builder-rofi

    volumes:
      - ./target:/target

    # tty: true
    # stdin_open: true

    command: >
      /bin/bash -c
      "cd /target
      && ( git clone https://github.com/davatorium/rofi.git . || : ; )
      && git fetch -apt
      && git checkout 4110e98
      && rm -rf build .prefix
      && meson setup build
      && ninja -C build"

    build:
      context: .
      dockerfile_inline: |
        FROM docker.io/ubuntu:25.04

        RUN apt-get --yes update
        RUN apt-get --yes update && apt-get --yes install git                 \
          meson ninja-build gcc make automake pkg-config flex bison cmake     \
          libwayland-*                                                        \
          libpango1.0-dev libpangocairo-1.0-0 libcairo2 libglib2.0-dev        \
          libgdk-pixbuf-2.0-dev libstartup-notification0-dev libxkbcommon-dev \
          wayland-protocols
