# ref: https://github.com/zefr0x/ianny?tab=readme-ov-file#config
# 
# All numeric values are in seconds

[timer]
# Enabling this will only consider user input alone for idle
# state, e.g. you will not have breaks when watching videos 
# or playing music without any user input
ignore_idle_inhibitors = false

# Timer will stop and reset when you are
# idle for this amount of seconds
idle_timeout = 240

# Active durations that activates a break
short_break_timeout = 1800
long_break_timeout = 3600

# Breaks durations
short_break_duration = 120
long_break_duration = 240

[notification]
show_progress_bar = true
# Minimum delay of updating the progress bar
minimum_update_delay = 10
