# We accept the following hadolint issues because
# this is a build container.
#
# hadolint global ignore=DL3002,DL3008,DL3009,DL3013,DL3059,DL4006

# cspell: disable

# Ubuntu 26.04
FROM docker.io/ubuntu@sha256:b7f48194d4d8b763a478a621cdc81c27be222ba2206ca3ca6bc42b49685f3d9e
USER root

# -----------------------------------------------
# ----  Environment  ----------------------------
# -----------------------------------------------

WORKDIR /src

ENV __INSTALLATION_PREFIX=/usr/local
ENV __TOOLCHAIN_VERSION_GO=1.26.4
ENV __TOOLCHAIN_VERSION_MESON=1.11.2
ENV __TOOLCHAIN_VERSION_RUST=1.97.0

ENV CARGO_HOME=/root/.cache/rust/${__TOOLCHAIN_VERSION_RUST}/cargo/home
ENV RUSTUP_HOME=/root/.cache/rust/${__TOOLCHAIN_VERSION_RUST}/rustup/home

ENV DEBIAN_FRONTEND=noninteractive
ENV LD_LIBRARY_PATH=/usr/local/lib/x86_64-linux-gnu
ENV PATH=${CARGO_HOME}/bin:/root/.local/bin:/usr/local/go/bin:$PATH

# -----------------------------------------------
# ----  Installation of General Packages  -------
# -----------------------------------------------

RUN apt-get update \
    && apt-get dist-upgrade --quiet --yes \
    && apt-get install --quiet --yes --no-install-recommends \
        bash-completion \
        ca-certificates \
        curl \
        file \
        openssl \
        tar \
        wget \
        xz-utils \
        \
        bison \
        build-essential \
        clang \
        cmake \
        flex \
        gcc \
        gettext \
        git \
        nasm \
        ninja-build \
        pkg-config \
        scdoc \
        \
        lua5.4 \
        liblua5.4-0 \
        liblua5.4-dev \
        \
        python3 \
        python3-docutils \
        python3-setuptools \
        python3-dev \
        \
        dbus \
        libdrm-dev \
        libffi-dev \
        liblz4-dev \
        libpam0g-dev \
        libpcre2-dev \
        librsvg2-dev \
        libseccomp-dev \
        libssl-dev \
        libudev-dev \
        shared-mime-info \
        \
        systemd \
        systemd-dev \
        libsystemd-dev

# -----------------------------------------------
# ----  Copy Build Scripts (Except Custom)  -----
# -----------------------------------------------

COPY \
    build_scripts/apt_install \
    build_scripts/build       \
    build_scripts/git_clone   \
    build_scripts/__log       \
    /root/.local/bin/

# -----------------------------------------------
# ----  Toolchain Setup  ------------------------
# -----------------------------------------------

RUN __log "Setting up UV (Python)"                                                                     \
    && curl -sSfL https://astral.sh/uv/install.sh | sh                                                 \
    && uv tool install "meson==${__TOOLCHAIN_VERSION_MESON}"                                           \
    \
    && __log "Setting up Rust"                                                                         \
    && { [ -d "${CARGO_HOME}" ] || curl -sSfL https://sh.rustup.rs                                     \
        | sh -s -- -y --default-toolchain "${__TOOLCHAIN_VERSION_RUST}" ; }                            \
    \
    && __log "Setting up Go"                                                                           \
    && mkdir -p "/root/.cache/go/${__TOOLCHAIN_VERSION_GO}"                                            \
    && { [ -e "/root/.cache/go/${__TOOLCHAIN_VERSION_GO}/go.tar.gz" ] ||                               \
        curl -sSfL -o "/root/.cache/go/${__TOOLCHAIN_VERSION_GO}/go.tar.gz"                            \
            "https://go.dev/dl/go${__TOOLCHAIN_VERSION_GO}.linux-amd64.tar.gz" ; }                     \
    && tar xf "/root/.cache/go/${__TOOLCHAIN_VERSION_GO}/go.tar.gz" -C /usr/local                      \
    \
    && __log "Setting up git"                                                                          \
    && git config --global advice.detachedHead false

# -----------------------------------------------
# ----  Actual Build  ---------------------------
# -----------------------------------------------

# ? Wayland

RUN git_clone https://gitlab.freedesktop.org/wayland/wayland.git 1.26.0 \
    && git_clone https://gitlab.freedesktop.org/wayland/wayland-protocols.git 1.49

RUN build wayland meson_ninja              \
        -D libraries=true                  \
        -D scanner=true                    \
        -D tests=false                     \
        -D documentation=false             \
        -D dtd_validation=false            \
    && build wayland-protocols meson_ninja \
        -D tests=false

# ? Generic Dependencies

RUN git_clone https://gitlab.freedesktop.org/libinput/libinput.git 1.31.3 \
    && git_clone https://gitlab.freedesktop.org/pixman/pixman.git pixman-0.46.4

RUN apt_install libevdev-dev libmtdev-dev

RUN build libinput meson_ninja  \
        -D libwacom=false       \
        -D mtdev=false          \
        -D debug-gui=false      \
        -D tests=false          \
        -D documentation=false  \
    && build pixman meson_ninja \
        -D tests=disabled       \
        -D demos=disabled

# ? X11

RUN git_clone https://gitlab.freedesktop.org/xorg/proto/xorgproto.git xorgproto-2025.1 \
    && git_clone https://gitlab.freedesktop.org/xorg/xserver.git xwayland-24.1.13

RUN apt_install           \
        libx11-dev        \
        libxshmfence-dev  \
        x11-xkb-utils     \
        xutils-dev        \
        libgbm-dev        \
        libegl-dev        \
        libgl-dev         \
        libpixman-1-dev   \
        libxkbfile-dev    \
        libxkbfile-dev    \
        libxfont-dev      \
        libxcvt-dev       \
        libepoxy-dev      \
        mesa-common-dev   \
        libtirpc-dev      \
        libxcb-dri3-dev   \
        libxcb-xinput-dev \
        libxcb-sync-dev   \
        libxcb-damage0-dev

RUN build xorgproto meson_ninja  \
    && build xserver meson_ninja \
        -D docs=false            \
        -D glamor=true           \
        -D dri3=true             \
        -D drm=true              \
        -D glx=true

# ? SwayFX

RUN git_clone https://gitlab.freedesktop.org/wlroots/wlroots.git 0.20.2
RUN apt_install                 \
        libxkbcommon-dev        \
        libvulkan-dev           \
        glslang-dev             \
        glslang-tools           \
        liblcms2-dev            \
        libseat-dev             \
        hwdata                  \
        libdisplay-info-dev     \
        libgles-dev             \
        libliftoff-dev          \
        libxcb-present-dev      \
        libxcb-composite0-dev   \
        libxcb-render-util0-dev \
        libxcb-shm0-dev         \
        libxcb-xfixes0-dev      \
        libxcb-xinput-dev       \
        libxcb-ewmh-dev         \
        libxcb-icccm4-dev       \
        libxcb-res0-dev
RUN build wlroots meson_ninja        \
        -D xwayland=enabled          \
        -D examples=false            \
        -D renderers=gles2,vulkan    \
        -D backends=drm,libinput,x11 \
        -D session=enabled           \
        -D color-management=enabled  \
        -D libliftoff=enabled

RUN git_clone https://github.com/wlrfx/scenefx.git main
RUN build scenefx meson_ninja \
        -D examples=false     \
        -D color-management=enabled

RUN apt_install                    \
        libjson-c-dev              \
        libcairo-dev               \
        libgdk-pixbuf-2.0-dev      \
        libgdk-pixbuf-xlib-2.0-dev \
        libpango1.0-dev
RUN git_clone https://github.com/WillPower3309/swayfx.git master
RUN build swayfx meson_ninja          \
        -D default-wallpaper=false    \
        -D zsh-completions=false      \
        -D bash-completions=true      \
        -D fish-completions=false     \
        -D swaybar=false              \
        -D swaynag=false              \
        -D tray=enabled               \
        -D gdk-pixbuf=enabled         \
        -D man-pages=enabled          \
        -D sd-bus-provider=libsystemd

# ? xdg-desktop-portal(s)

RUN git_clone https://gitlab.gnome.org/GNOME/libdex.git main
RUN apt_install               \
        gobject-introspection \
        liburing-dev          \
        valac
RUN build libdex meson_ninja    \
        -Dstack-protector=true  \
        -Dvapi=true             \
        -Dintrospection=enabled \
        -Dliburing=enabled      \
        -Deventfd=enabled       \
        -Dgdbus=enabled

RUN git_clone https://github.com/flatpak/xdg-desktop-portal.git main
RUN apt_install                          \
        libdbus-1-dev                    \
        libfuse3-dev                     \
        libgeoclue-2-dev                 \
        libgstreamer1.0-dev              \
        libgstreamer-plugins-base1.0-dev \
        libjson-glib-dev                 \
        libpipewire-0.3-dev              \
        libumockdev-dev                  \
        libwireplumber-0.5-dev
RUN build xdg-desktop-portal meson_ninja     \
        -Dgeoclue=enabled                    \
        -Dgudev=enabled                      \
        -Dsystemd=enabled                    \
        -Ddocumentation=disabled             \
        -Dtests=disabled                     \
        -Dman-pages=enabled                  \
        -Dsandboxed-image-validation=enabled \
        -Dsandboxed-sound-validation=enabled

RUN git_clone https://github.com/emersion/xdg-desktop-portal-wlr.git master
RUN apt_install libinih-dev
RUN build xdg-desktop-portal-wlr meson_ninja \
        -Dsd-bus-provider=libsystemd         \
        -Dsystemd=enabled                    \
        -Dman-pages=enabled

# ? Associates

# * 1. Default builds

RUN git_clone https://codeberg.org/tytan652/door-knocker.git main              \
    && git_clone https://gitlab.freedesktop.org/emersion/grim.git v1.5.0       \
    && git_clone https://github.com/davatorium/rofi.git next                   \
    && git_clone https://github.com/emersion/slurp.git v1.5.0                  \
    && git_clone https://github.com/ErikReider/SwayAudioIdleInhibit.git main   \
    && git_clone https://github.com/swaywm/swaybg.git v1.2.2                   \
    && git_clone https://github.com/swaywm/swayidle.git master                 \
    && git_clone https://github.com/swaywm/swaylock.git v1.8.6                 \
    && git_clone https://github.com/ErikReider/SwayNotificationCenter.git main \
    && git_clone https://github.com/Alexays/Waybar.git master                  \
    && git_clone https://github.com/kennylevinsen/wlsunset.git master

RUN apt_install blueprint-compiler desktop-file-utils libgtk-4-dev libadwaita-1-dev
RUN build door-knocker meson_ninja

RUN build grim meson_ninja

RUN build rofi meson_ninja -D xcb=disabled -D wayland=enabled

RUN build slurp meson_ninja

RUN apt_install libpulse-dev
RUN build SwayAudioIdleInhibit meson_ninja -D logind-provider=systemd

RUN build swaybg meson_ninja

RUN build swayidle meson_ninja

RUN build swaylock meson_ninja -D pam=enabled

RUN apt_install                \
        valac                  \
        sassc                  \
        libgtk-3-dev           \
        libhandy-1-dev         \
        libgranite-7-dev       \
        libgtk-layer-shell-dev \
        libgtk4-layer-shell-dev
RUN build SwayNotificationCenter meson_ninja \
        -D systemd-service=false             \
        -D zsh-completions=false             \
        -D fish-completions=false

RUN apt_install                \
        libdbusmenu-gtk3-dev   \
        libfmt-dev             \
        libgirepository1.0-dev \
        libgtk-3-dev           \
        libgtkmm-3.0-dev       \
        libinput-dev           \
        libjsoncpp-dev         \
        libmpdclient-dev       \
        libnl-3-dev            \
        libnl-genl-3-dev       \
        libpulse-dev           \
        libsigc++-2.0-dev      \
        libspdlog-dev          \
        scdoc                  \
        upower                 \
        libxkbregistry-dev     \
        libjack-dev            \
        libsndio-dev           \
        libupower-glib-dev
RUN build Waybar meson_ninja    \
        -D libinput=enabled     \
        -D libnl=enabled        \
        -D libudev=enabled      \
        -D libevdev=enabled     \
        -D pipewire=enabled     \
        -D systemd=disabled     \
        -D dbusmenu-gtk=enabled \
        -D man-pages=enabled    \
        -D rfkill=enabled       \
        -D tests=disabled       \
        -D jack=enabled         \
        -D wireplumber=enabled  \
        -D cava=disabled        \
        -D login-proxy=true

RUN build wlsunset meson_ninja

# * 2. Custom builds

RUN git_clone https://github.com/alacritty/alacritty.git v0.17.0                       \
    && git_clone https://codeberg.org/LGFae/awww.git main                              \
    && git_clone https://github.com/zefr0x/ianny.git v2.1.3                            \
    && git_clone https://github.com/blurrycat/lightctl.git main                        \
    && git_clone https://github.com/Satty-org/Satty.git v0.21.1                        \
    && git_clone https://gitlab.com/w0lff/shikane.git master                           \
    && git_clone https://github.com/rafaelrc7/wayland-pipewire-idle-inhibit.git master \
    && git_clone https://github.com/russelltg/wl-screenrec.git main                    \
    && git_clone https://github.com/AMNatty/wleave.git development                     \
    && git_clone https://github.com/nwg-piotr/nwg-look.git main

COPY build_scripts/custom_build /root/.local/bin/cb

RUN cb alacritty build_alacritty

RUN apt_install liblz4-dev
RUN cb awww build_awww

RUN cb ianny build_ianny
RUN cb lightctl build_lightctl

RUN apt_install libgraphene-1.0-dev
RUN cb Satty build_satty

RUN cb shikane build_shikane

RUN cb wayland-pipewire-idle-inhibit build_wayland_pipewire_idle_inhibit

RUN apt_install libavutil-dev libavformat-dev libavfilter-dev libavdevice-dev
RUN cb wl-screenrec build_wl_screenrec

RUN cb wleave build_wleave

RUN cb nwg-look build_nwg_look

# -----------------------------------------------
# ----  Final Adjustments  ----------------------
# -----------------------------------------------

COPY build_scripts/finalize_runtime_libs /root/.local/bin/finalize_runtime_libs
RUN finalize_runtime_libs

# ! Take care when adjusting these paths;
# ! especially libc + ld-linux MUST remain in sync
# ! and MUST be the correct files from the correct place.
WORKDIR /usr/local/lib/x86_64-linux-gnu
RUN cp -r /lib/x86_64-linux-gnu/pulseaudio/ .                         \
    && ln -s pulseaudio/libpulsecommon-17.0.so libpulsecommon-17.0.so \
    && cp                                                             \
        /usr/lib/x86_64-linux-gnu/libc.so.6                           \
        /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2                \
        /usr/lib/x86_64-linux-gnu/libdl.so.2                          \
        /usr/lib/x86_64-linux-gnu/libpthread.so.0                     \
        /usr/lib/x86_64-linux-gnu/libdisplay-info.so.3                \
        .                                                             \
    && apt_install glycin-loaders                                     \
    && cp -r /usr/libexec/glycin-loaders /usr/local/libexec/          \
    && cp -r /usr/share/glycin-loaders   /usr/local/share/            \
    && sed -i -E 's|/usr/(libexec/glycin-loaders)|/usr/local/\1|g'    \
        /usr/local/share/glycin-loaders/*/conf.d/*.conf
